CC ?= clang
SHELL ?= /bin/sh

INCDIR = ../include
ASAN_CCFLAGS = -Wall -Wextra -g -fno-omit-frame-pointer -fsanitize=address

.PHONY: asan
asan: CFLAGS = $(ASAN_CCFLAGS) -I$(INCDIR)
asan: a_libft.a

a_libft.a: pf_printf_g.o
a_libft.a: ft_strrchr.o
a_libft.a: ft_putstr.o
a_libft.a: ft_islower.o
a_libft.a: ft_strcmp.o
a_libft.a: pf_printf_k.o
a_libft.a: ft_strlcat.o
a_libft.a: ft_strchrnul.o
a_libft.a: ft_memcpy.o
a_libft.a: pf_printf_lg.o
a_libft.a: hash_create.o
a_libft.a: ft_realloc.o
a_libft.a: pf_printf_dtoa_lf.o
a_libft.a: ft_memmove.o
a_libft.a: ft_strsplit.o
a_libft.a: ft_lstadd_tail.o
a_libft.a: pf_printf_ls.o
a_libft.a: pf_printf_dtoa_lg_le.o
a_libft.a: ft_isspace.o
a_libft.a: fq_queue.o
a_libft.a: pf_printf_g_e.o
a_libft.a: ft_strcspn.o
a_libft.a: ft_strncpy.o
a_libft.a: ft_strjoin_free.o
a_libft.a: ft_wordcount.o
a_libft.a: ft_lstmap.o
a_libft.a: pf_printf_c.o
a_libft.a: pf_printf_dtoa_lg_lf.o
a_libft.a: ft_lstadd.o
a_libft.a: pf_conv.o
a_libft.a: ft_striter.o
a_libft.a: ft_strstr.o
a_libft.a: ft_isdigit.o
a_libft.a: ft_putnbr.o
a_libft.a: ft_isupper.o
a_libft.a: ft_memccpy.o
a_libft.a: ft_strspn.o
a_libft.a: ft_getenv.o
a_libft.a: pf_printf_lg_le.o
a_libft.a: pf_per.o
a_libft.a: pf_printf_itoa_a.o
a_libft.a: ft_strdel.o
a_libft.a: pf_printf_itoa_base.o
a_libft.a: ft_strchri.o
a_libft.a: ft_memchr.o
a_libft.a: ft_bzero.o
a_libft.a: pf_printf_dtoa_a.o
a_libft.a: pf_printf_n.o
a_libft.a: pf_printf_lf.o
a_libft.a: ft_wstrcpy.o
a_libft.a: pf_getutype2.o
a_libft.a: ft_strtok.o
a_libft.a: pf_buffer.o
a_libft.a: pf_printf_lg_lf.o
a_libft.a: pf_printf_a.o
a_libft.a: hash_bucket.o
a_libft.a: ft_isalnum.o
a_libft.a: ft_putstr_fd.o
a_libft.a: pf_printf_dtoa_la.o
a_libft.a: ft_puterr.o
a_libft.a: hash_search.o
a_libft.a: ft_lstiter.o
a_libft.a: ft_lstrev.o
a_libft.a: ft_lstdelone.o
a_libft.a: ft_toupper.o
a_libft.a: ft_strcpy.o
a_libft.a: hash_walk.o
a_libft.a: ft_isblank.o
a_libft.a: ft_strndup.o
a_libft.a: pf_printf_dtoa_le.o
a_libft.a: ft_lstnew.o
a_libft.a: pf_getutype.o
a_libft.a: pf_printf_dtoa_f.o
a_libft.a: pf_printf_u.o
a_libft.a: ft_strdup.o
a_libft.a: dq_deque.o
a_libft.a: ft_putnbr_fd.o
a_libft.a: pf_printf_itoa.o
a_libft.a: ft_striteri.o
a_libft.a: ft_ostrlen.o
a_libft.a: ft_dtoa.o
a_libft.a: pf_printf_ind.o
a_libft.a: ft_strmap.o
a_libft.a: pf_printf_d.o
a_libft.a: ft_putendl_fd.o
a_libft.a: ft_memdel.o
a_libft.a: ft_strnstr.o
a_libft.a: ft_putchar.o
a_libft.a: pf_printf_dtoa_e.o
a_libft.a: hash_size.o
a_libft.a: ft_isascii.o
a_libft.a: ft_strlen.o
a_libft.a: ft_strsub.o
a_libft.a: ft_strtok_r.o
a_libft.a: pf_flags.o
a_libft.a: pf_printf_e.o
a_libft.a: ft_strnew.o
a_libft.a: ft_memalloc.o
a_libft.a: pf_printf_dtoa_lent.o
a_libft.a: hash_remove.o
a_libft.a: ft_putendl.o
a_libft.a: ft_strncat.o
a_libft.a: pf_getstype2.o
a_libft.a: ft_itoa.o
a_libft.a: pf_pars.o
a_libft.a: pf_printf_dtoa_g_f.o
a_libft.a: ft_getopt.o
a_libft.a: pf_printf_x.o
a_libft.a: hash_insert.o
a_libft.a: hash_string.o
a_libft.a: ft_strncmp.o
a_libft.a: ft_atoi_base.o
a_libft.a: pf_getstype.o
a_libft.a: ft_memcmp.o
a_libft.a: pf_printf_le.o
a_libft.a: ft_strtrim.o
a_libft.a: ft_strequ.o
a_libft.a: pf_printf_dtoa_g_e.o
a_libft.a: hash_dispose.o
a_libft.a: ft_putchar_fd.o
a_libft.a: get_next_line.o
a_libft.a: ft_memset.o
a_libft.a: ft_isalpha.o
a_libft.a: ft_itoa_base.o
a_libft.a: ft_strcat.o
a_libft.a: ft_tolower.o
a_libft.a: pf_printf.o
a_libft.a: pf_printf_putchar_fd.o
a_libft.a: pf_printf_s.o
a_libft.a: pf_fprintf.o
a_libft.a: ft_strnequ.o
a_libft.a: ft_strjoin.o
a_libft.a: ft_atoi.o
a_libft.a: ft_strclr.o
a_libft.a: pf_printf_o.o
a_libft.a: hash_copy.o
a_libft.a: hash_flush.o
a_libft.a: pf_printf_g_f.o
a_libft.a: pf_printf_ktoa.o
a_libft.a: ft_strmapi.o
a_libft.a: pf_printf_p.o
a_libft.a: pf_printf_b.o
a_libft.a: pf_printf_getdaymonth.o
a_libft.a: ft_isprint.o
a_libft.a: ft_lstdel.o
a_libft.a: pf_printf_strnew.o
a_libft.a: pf_color.o
a_libft.a: pf_printf_f.o
a_libft.a: ft_strchr.o
a_libft.a: ft_nbrlen_base.o
a_libft.a: pf_printf_la.o
a_libft.a: pf_printf_dtoa_ent.o
a_libft.a: getdelim.o
a_libft.a: pf_convspe.o
