CC = clang
SHELL = /bin/sh

INCDIR = ../include
DEBUG_CCFLAGS = -Wall -Wextra -g -fno-omit-frame-pointer

.PHONY: debug
debug: CFLAGS = $(DEBUG_CCFLAGS) -I$(INCDIR)
debug: d_libft.a

d_libft.a: pf_printf_g.o
d_libft.a: ft_strrchr.o
d_libft.a: ft_putstr.o
d_libft.a: ft_islower.o
d_libft.a: ft_strcmp.o
d_libft.a: pf_printf_k.o
d_libft.a: ft_strlcat.o
d_libft.a: ft_strchrnul.o
d_libft.a: ft_memcpy.o
d_libft.a: pf_printf_lg.o
d_libft.a: hash_create.o
d_libft.a: ft_realloc.o
d_libft.a: pf_printf_dtoa_lf.o
d_libft.a: ft_memmove.o
d_libft.a: ft_strsplit.o
d_libft.a: ft_lstadd_tail.o
d_libft.a: pf_printf_ls.o
d_libft.a: pf_printf_dtoa_lg_le.o
d_libft.a: ft_isspace.o
d_libft.a: pf_printf_g_e.o
d_libft.a: ft_strcspn.o
d_libft.a: ft_strncpy.o
d_libft.a: ft_strjoin_free.o
d_libft.a: ft_wordcount.o
d_libft.a: ft_lstmap.o
d_libft.a: pf_printf_c.o
d_libft.a: pf_printf_dtoa_lg_lf.o
d_libft.a: ft_lstadd.o
d_libft.a: pf_conv.o
d_libft.a: ft_striter.o
d_libft.a: ft_strstr.o
d_libft.a: ft_isdigit.o
d_libft.a: ft_putnbr.o
d_libft.a: ft_isupper.o
d_libft.a: ft_memccpy.o
d_libft.a: ft_strspn.o
d_libft.a: ft_getenv.o
d_libft.a: pf_printf_lg_le.o
d_libft.a: pf_per.o
d_libft.a: pf_printf_itoa_a.o
d_libft.a: ft_strdel.o
d_libft.a: pf_printf_itoa_base.o
d_libft.a: ft_strchri.o
d_libft.a: ft_memchr.o
d_libft.a: ft_bzero.o
d_libft.a: pf_printf_dtoa_a.o
d_libft.a: pf_printf_n.o
d_libft.a: pf_printf_lf.o
d_libft.a: ft_wstrcpy.o
d_libft.a: pf_getutype2.o
d_libft.a: ft_strtok.o
d_libft.a: pf_buffer.o
d_libft.a: pf_printf_lg_lf.o
d_libft.a: pf_printf_a.o
d_libft.a: hash_bucket.o
d_libft.a: ft_isalnum.o
d_libft.a: ft_putstr_fd.o
d_libft.a: pf_printf_dtoa_la.o
d_libft.a: ft_puterr.o
d_libft.a: hash_search.o
d_libft.a: ft_lstiter.o
d_libft.a: ft_lstrev.o
d_libft.a: ft_lstdelone.o
d_libft.a: ft_toupper.o
d_libft.a: ft_strcpy.o
d_libft.a: hash_walk.o
d_libft.a: ft_isblank.o
d_libft.a: ft_strndup.o
d_libft.a: pf_printf_dtoa_le.o
d_libft.a: ft_lstnew.o
d_libft.a: pf_getutype.o
d_libft.a: pf_printf_dtoa_f.o
d_libft.a: pf_printf_u.o
d_libft.a: ft_strdup.o
d_libft.a: dq_deque.o
d_libft.a: ft_putnbr_fd.o
d_libft.a: pf_printf_itoa.o
d_libft.a: ft_striteri.o
d_libft.a: ft_ostrlen.o
d_libft.a: ft_dtoa.o
d_libft.a: pf_printf_ind.o
d_libft.a: ft_strmap.o
d_libft.a: pf_printf_d.o
d_libft.a: ft_putendl_fd.o
d_libft.a: ft_memdel.o
d_libft.a: ft_strnstr.o
d_libft.a: ft_putchar.o
d_libft.a: pf_printf_dtoa_e.o
d_libft.a: hash_size.o
d_libft.a: ft_isascii.o
d_libft.a: ft_strlen.o
d_libft.a: ft_strsub.o
d_libft.a: ft_strtok_r.o
d_libft.a: pf_flags.o
d_libft.a: pf_printf_e.o
d_libft.a: ft_strnew.o
d_libft.a: ft_memalloc.o
d_libft.a: pf_printf_dtoa_lent.o
d_libft.a: hash_remove.o
d_libft.a: ft_putendl.o
d_libft.a: ft_strncat.o
d_libft.a: pf_getstype2.o
d_libft.a: ft_itoa.o
d_libft.a: pf_pars.o
d_libft.a: pf_printf_dtoa_g_f.o
d_libft.a: ft_getopt.o
d_libft.a: pf_printf_x.o
d_libft.a: hash_insert.o
d_libft.a: hash_string.o
d_libft.a: ft_strncmp.o
d_libft.a: ft_atoi_base.o
d_libft.a: pf_getstype.o
d_libft.a: ft_memcmp.o
d_libft.a: pf_printf_le.o
d_libft.a: ft_strtrim.o
d_libft.a: ft_strequ.o
d_libft.a: pf_printf_dtoa_g_e.o
d_libft.a: hash_dispose.o
d_libft.a: ft_putchar_fd.o
d_libft.a: get_next_line.o
d_libft.a: ft_memset.o
d_libft.a: ft_isalpha.o
d_libft.a: ft_itoa_base.o
d_libft.a: ft_strcat.o
d_libft.a: ft_tolower.o
d_libft.a: pf_printf.o
d_libft.a: pf_printf_putchar_fd.o
d_libft.a: pf_printf_s.o
d_libft.a: pf_fprintf.o
d_libft.a: ft_strnequ.o
d_libft.a: ft_strjoin.o
d_libft.a: ft_atoi.o
d_libft.a: ft_strclr.o
d_libft.a: pf_printf_o.o
d_libft.a: hash_copy.o
d_libft.a: hash_flush.o
d_libft.a: pf_printf_g_f.o
d_libft.a: pf_printf_ktoa.o
d_libft.a: ft_strmapi.o
d_libft.a: pf_printf_p.o
d_libft.a: pf_printf_b.o
d_libft.a: pf_printf_getdaymonth.o
d_libft.a: ft_isprint.o
d_libft.a: ft_lstdel.o
d_libft.a: pf_printf_strnew.o
d_libft.a: pf_color.o
d_libft.a: pf_printf_f.o
d_libft.a: ft_strchr.o
d_libft.a: ft_nbrlen_base.o
d_libft.a: pf_printf_la.o
d_libft.a: pf_printf_dtoa_ent.o
d_libft.a: getdelim.o
d_libft.a: pf_convspe.o
