CC ?= clang
SHELL ?= /bin/sh
RM ?= rm -f

INCDIR = ../include
CCFLAGS = -Wall -Wextra -Werror

.PHONY: all
all: CFLAGS = $(CCFLAGS) -I$(INCDIR)
all: libft.a

libft.a: pf_printf_g.o
libft.a: ft_strrchr.o
libft.a: ft_putstr.o
libft.a: ft_islower.o
libft.a: ft_strcmp.o
libft.a: pf_printf_k.o
libft.a: ft_strlcat.o
libft.a: ft_strchrnul.o
libft.a: ft_memcpy.o
libft.a: pf_printf_lg.o
libft.a: hash_create.o
libft.a: ft_realloc.o
libft.a: pf_printf_dtoa_lf.o
libft.a: ft_memmove.o
libft.a: ft_strsplit.o
libft.a: ft_lstadd_tail.o
libft.a: pf_printf_ls.o
libft.a: pf_printf_dtoa_lg_le.o
libft.a: ft_isspace.o
libft.a: fq_queue.o
libft.a: pf_printf_g_e.o
libft.a: ft_strcspn.o
libft.a: ft_strncpy.o
libft.a: ft_strjoin_free.o
libft.a: ft_wordcount.o
libft.a: ft_lstmap.o
libft.a: pf_printf_c.o
libft.a: pf_printf_dtoa_lg_lf.o
libft.a: ft_lstadd.o
libft.a: pf_conv.o
libft.a: ft_striter.o
libft.a: ft_strstr.o
libft.a: ft_isdigit.o
libft.a: ft_putnbr.o
libft.a: ft_isupper.o
libft.a: ft_memccpy.o
libft.a: ft_strspn.o
libft.a: ft_getenv.o
libft.a: pf_printf_lg_le.o
libft.a: pf_per.o
libft.a: pf_printf_itoa_a.o
libft.a: ft_strdel.o
libft.a: pf_printf_itoa_base.o
libft.a: ft_strchri.o
libft.a: ft_memchr.o
libft.a: ft_bzero.o
libft.a: pf_printf_dtoa_a.o
libft.a: pf_printf_n.o
libft.a: pf_printf_lf.o
libft.a: ft_wstrcpy.o
libft.a: pf_getutype2.o
libft.a: ft_strtok.o
libft.a: pf_buffer.o
libft.a: pf_printf_lg_lf.o
libft.a: pf_printf_a.o
libft.a: hash_bucket.o
libft.a: ft_isalnum.o
libft.a: ft_putstr_fd.o
libft.a: pf_printf_dtoa_la.o
libft.a: ft_puterr.o
libft.a: hash_search.o
libft.a: ft_lstiter.o
libft.a: ft_lstrev.o
libft.a: ft_lstdelone.o
libft.a: ft_toupper.o
libft.a: ft_strcpy.o
libft.a: hash_walk.o
libft.a: ft_isblank.o
libft.a: ft_strndup.o
libft.a: pf_printf_dtoa_le.o
libft.a: ft_lstnew.o
libft.a: pf_getutype.o
libft.a: pf_printf_dtoa_f.o
libft.a: pf_printf_u.o
libft.a: ft_strdup.o
libft.a: dq_deque.o
libft.a: ft_putnbr_fd.o
libft.a: pf_printf_itoa.o
libft.a: ft_striteri.o
libft.a: ft_ostrlen.o
libft.a: ft_dtoa.o
libft.a: pf_printf_ind.o
libft.a: ft_strmap.o
libft.a: pf_printf_d.o
libft.a: ft_putendl_fd.o
libft.a: ft_memdel.o
libft.a: ft_strnstr.o
libft.a: ft_putchar.o
libft.a: pf_printf_dtoa_e.o
libft.a: hash_size.o
libft.a: ft_isascii.o
libft.a: ft_strlen.o
libft.a: ft_strsub.o
libft.a: ft_strtok_r.o
libft.a: pf_flags.o
libft.a: pf_printf_e.o
libft.a: ft_strnew.o
libft.a: ft_memalloc.o
libft.a: pf_printf_dtoa_lent.o
libft.a: hash_remove.o
libft.a: ft_putendl.o
libft.a: ft_strncat.o
libft.a: pf_getstype2.o
libft.a: ft_itoa.o
libft.a: pf_pars.o
libft.a: pf_printf_dtoa_g_f.o
libft.a: ft_getopt.o
libft.a: pf_printf_x.o
libft.a: hash_insert.o
libft.a: hash_string.o
libft.a: ft_strncmp.o
libft.a: ft_atoi_base.o
libft.a: pf_getstype.o
libft.a: ft_memcmp.o
libft.a: pf_printf_le.o
libft.a: ft_strtrim.o
libft.a: ft_strequ.o
libft.a: pf_printf_dtoa_g_e.o
libft.a: hash_dispose.o
libft.a: ft_putchar_fd.o
libft.a: get_next_line.o
libft.a: ft_memset.o
libft.a: ft_isalpha.o
libft.a: ft_itoa_base.o
libft.a: ft_strcat.o
libft.a: ft_tolower.o
libft.a: pf_printf.o
libft.a: pf_printf_putchar_fd.o
libft.a: pf_printf_s.o
libft.a: pf_fprintf.o
libft.a: ft_strnequ.o
libft.a: ft_strjoin.o
libft.a: ft_atoi.o
libft.a: ft_strclr.o
libft.a: pf_printf_o.o
libft.a: hash_copy.o
libft.a: hash_flush.o
libft.a: pf_printf_g_f.o
libft.a: pf_printf_ktoa.o
libft.a: ft_strmapi.o
libft.a: pf_printf_p.o
libft.a: pf_printf_b.o
libft.a: pf_printf_getdaymonth.o
libft.a: ft_isprint.o
libft.a: ft_lstdel.o
libft.a: pf_printf_strnew.o
libft.a: pf_color.o
libft.a: pf_printf_f.o
libft.a: ft_strchr.o
libft.a: ft_nbrlen_base.o
libft.a: pf_printf_la.o
libft.a: pf_printf_dtoa_ent.o
libft.a: getdelim.o
libft.a: pf_convspe.o
